# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 22:04
from __future__ import unicode_literals

from django.db import migrations, models


def create_continent(apps, schema_editor):
    Continent = apps.get_model("continents", "Continent")
    Continent.objects.create(name="America", color="#00000", translate="am")
    Continent.objects.create(name="Asia", color="#EE65EE", translate="as")
    Continent.objects.create(name="Antartida", color="#FFFF00", translate="an")
    Continent.objects.create(name="Europa", color="#F1D142", translate="eu")
    Continent.objects.create(name="Africa", color="#F04261", translate="af")
    Continent.objects.create(name="Oceania", color="#EE65DD", translate="oc")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_continent),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(choices=[('Colombia', 'CO'), ('EEAA', 'USA'), ('Mexico', 'MX')], max_length=3)),
            ],
        ),
    ]
