# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 13:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_auto_20180329_0720'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='country',
            managers=[
                ('active_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
