# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_auto_20180329_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(choices=[('CO', 'Colombia'), ('USA', 'EEAA'), ('MX', 'Mexico')], max_length=3),
        ),
    ]
